
package com.example.ves.tests;

import static io.restassured.RestAssured.given;

import static org.junit.Assert.assertNotNull;
import static org.junit.Assert.assertTrue;

import javax.jms.JMSException;
import javax.jms.Message;
import javax.jms.ObjectMessage;

import org.junit.Test;

import com.example.ves.util.VesBodyGenerator;

import io.restassured.http.ContentType;

/**
 * Contains integration tests for the VES Listener.
 */
public class VesListenerIT extends BaseClass {

    private static String VES_SIMULATOR_URI = "http://localhost:5000/simulator/event";
    private static int TIME_TO_WAIT_MILLISECS = 1000;

    @Test
    public void GIVEN_singleVesEventGenerated_THEN_singleJmsMessageProduced() throws JMSException {

        // GIVEN - a single VES event is generated by the simulator
        given().contentType(ContentType.JSON)
                .body(VesBodyGenerator.getEvent())
                .post(VES_SIMULATOR_URI)
                .then().assertThat().statusCode(202);

        // THEN - the listener receives the event and generates a JMS message for it
        final Message jmsMessage = consumer.receive(TIME_TO_WAIT_MILLISECS);
        assertNotNull("No message received", jmsMessage);
        assertTrue("Received message is not an ObjectMessage", jmsMessage instanceof ObjectMessage);
    }
}
