Feature: Test VES Listener

  Scenario: Generate JMS message for single VES event
    Given the URL for the VES simulator "http://localhost:5000/simulator/event"
    When a single VES event is generated by the simulator
    Then the response status code should be 202
    And the listener should generate a JMS message
