FROM nexus3.onap.org:10001/onap/org.onap.integration.nfsimulator.vesclient

ENV USE_CERTIFICATE_FOR_AUTHORIZATION=false

COPY ./templates /app/templates
COPY ./store /app/store
COPY ./properties/application.properties /app/application.properties

EXPOSE 5000
